trigger:
  batch: true
  branches:
    include:
      - "*"
  paths:
    include:
      - tests/*
      - templates/*
      - utilities/*
      - Initialize-SharedInfrastructureDeployment.ps1
      - azure-pipelines.yml

pr: none

workspace:
  clean: all

pool:
  name: "DAS - Continuous Deployment"
  demands:
    - npm
    - node.js

steps:
  - task: GitVersion@4
    displayName: GitVersion
  - script: |
      npm install eclint
      node ./node_modules/eclint/bin/eclint.js check
    displayName: "Validate editorconfig"
    workingDirectory: $(System.DefaultWorkingDirectory)
  - powershell: |
      ./tests/Start-UnitTest.ps1
    displayName: "Execute unit tests"
    failOnStderr: "true"
    workingDirectory:  $(System.DefaultWorkingDirectory)
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'NUnit'
      testResultsFiles: $(System.DefaultWorkingDirectory)\tests\Test-Pester.XML
    condition: succeededOrFailed()

  - task: CopyFiles@2
    displayName: "Copy Files to: $(build.artifactstagingdirectory)"
    inputs:
      Contents: |
        modules/**
        templates/**
        utilities/**
        Initialize-SharedInfrastructureDeployment.ps1
      TargetFolder: "$(build.artifactstagingdirectory)/publish"
      OverWrite: true

  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact"
    inputs:
      PathtoPublish: "$(build.artifactstagingdirectory)/publish"
