trigger:
  batch: true
  branches:
    include:
      - "*"
  paths:
    include:
      - tests/*
      - templates/*
      - utilities/*
      - Initialize-SharedInfrastructureDeployment.ps1

pr: none

stages:
  - stage: Build
    jobs:
      - job: "LintAndTest"
        pool:
          name: "DAS - Continuous Deployment"
          demands:
            - npm
            - node.js
        workspace:
          clean: all
        steps:
          - task: GitVersion@4
            displayName: GitVersion
          - script: |
              npm install eclint
              node ./node_modules/eclint/bin/eclint.js check
            displayName: "Validate editorconfig"
            workingDirectory: $(System.DefaultWorkingDirectory)
          - powershell: |
              ./tests/Start-UnitTest.ps1
            displayName: "Execute unit tests"
            failOnStderr: "true"
            workingDirectory:  $(System.DefaultWorkingDirectory)
          - task: PublishTestResults@2
            inputs:
              testResultsFormat: 'NUnit'
              testResultsFiles: $(System.DefaultWorkingDirectory)\tests\Test-Pester.XML
            condition: succeededOrFailed()

  - stage: Release
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    jobs:
    - deployment: "GitHubRelease"
      displayName: "Create Release in GitHub"
      pool:
        name: "DAS - Continuous Deployment"
      environment: GitHub
      strategy:
        runOnce:
          deploy:
            steps:
              - task: GitHubRelease@0
                inputs:
                  gitHubConnection: "SFA"
                  repositoryName: "$(Build.Repository.Name)"
                  action: "create"
                  target: "$(Build.SourceVersion)"
                  tagSource: "manual"
                  tag: "$(Build.BuildNumber)"
                  addChangeLog: true
                  assets: "$(System.DefaultWorkingDirectory)/Infrastructure-Scripts/**/*.ps1"
