trigger:
  batch: true
  branches:
    include:
      - "*"
  paths:
    include:
      - tests/*
      - templates/*
      - utilities/*
      - apim/*
      - Initialize-SharedInfrastructureDeployment.ps1
      - Initialize-ApimDeveloperPortal.ps1
      - azure-pipelines.yml

pr: none

workspace:
  clean: all

pool:
  name: "DAS - Continuous Integration Agents"
  demands:
    - npm
    - node.js

resources:
  repositories:
  - repository: self
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/0.3.31
    endpoint: SkillsFundingAgency

stages:
- stage: Build
  jobs:
  - template: pipeline-templates/job/code-build.yml
    parameters:
      SolutionBaseName: $(SolutionBaseName)
      BuildConfiguration: $(BuildConfiguration)
