trigger:
  batch: true
  branches:
    include:
      - "master"

pr: none

variables:
- group: Release Management Resources
- group: RELEASE das-shared-infrastructure

resources:
  repositories:
  - repository: self
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/3.0.16
    endpoint: SkillsFundingAgency
  - repository: das-platform-automation
    type: github
    name: SkillsFundingAgency/das-platform-automation
    ref: refs/tags/5.1.21
    endpoint: SkillsFundingAgency

stages:
- stage: Build
  jobs:
  - template: pipeline-templates/code-build.yml

- stage: Deploy_DTA
  dependsOn: Build
  displayName: Deploy to DTA
  variables:
  - group: DTA das-shared-infrastructure
  jobs:
  - template: pipeline-templates/deploy.yml
    parameters:
      ServiceConnection: SFA-DAS-DevTest-ARM
      Environment: DTA

- stage: Deploy_DEV
  dependsOn: Build
  displayName: Deploy to DEV
  variables:
  - group: DEV das-shared-infrastructure
  jobs:
  - template: pipeline-templates/deploy.yml
    parameters:
      ServiceConnection: SFA-DAS-DevTest-ARM
      Environment: DEV
      EnvironmentNames: AT TEST TEST2 DEMO

- stage: Deploy_PP
  dependsOn: Build
  displayName: Deploy to PP
  variables:
  - group: PREPROD das-shared-infrastructure
  jobs:
  - template: pipeline-templates/deploy.yml
    parameters:
      ServiceConnection: SFA-DIG-PreProd-ARM
      Environment: PP

- stage: Deploy_PRD
  dependsOn: Build
  displayName: Deploy to PRD
  variables:
  - group: PROD das-shared-infrastructure
  jobs:
  - template: pipeline-templates/deploy.yml
    parameters:
      ServiceConnection: SFA-DIG-Prod-ARM
      Environment: PRD

- stage: Deploy_MO
  dependsOn: Build
  displayName: Deploy to MO
  variables:
  - group: MO das-shared-infrastructure
  jobs:
  - template: pipeline-templates/deploy.yml
    parameters:
      ServiceConnection: SFA-ASM-ModelOffice-ARM
      Environment: MO