trigger:
  batch: true
  branches:
    include:
      - "*"

pr: none

jobs:
    - job: "Lint"
      displayName: "Validate editorconfig"
      pool:
        name: "DAS - Continuous Deployment"
      steps:
        - script: |
            npm install eclint
            node ./node_modules/eclint/bin/eclint.js check
          workingDirectory: $(System.DefaultWorkingDirectory)
    - deployment: "Release"
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
      displayName: "Create Release in GitHub"
      pool:
        name: "DAS - Continuous Deployment"
      environment: GitHub
      strategy:
        runOnce:
          deploy:
            steps:
              - task: GitVersion@4
                displayName: GitVersion
              - task: GitHubRelease@0
                inputs:
                  gitHubConnection: "SFA"
                  repositoryName: "$(Build.Repository.Name)"
                  action: "create"
                  target: "$(Build.SourceVersion)"
                  tagSource: "manual"
                  tag: "$(Build.BuildNumber)"
                  addChangeLog: true
