trigger:
  batch: true
  branches:
    include:
      - "*"
  paths:
    include:
      - templates/*
      - utilities/*
      - Initialize-SharedInfrastructureDeployment.ps1

pr: none

stages:
  - stage: Lint
    jobs:
      - job: "EditorConfigValidation"
        pool:
          name: "DAS - Continuous Deployment"
          demands:
            - npm
            - node.js
        workspace:
          clean: all
        steps:
          - script: |
              npm install eclint
              node ./node_modules/eclint/bin/eclint.js check
            displayName: "Validate editorconfig"
            workingDirectory: $(System.DefaultWorkingDirectory)

  - stage: Release
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    jobs:
    - deployment: "GitHubRelease"
      displayName: "Create Release in GitHub"
      pool:
        name: "DAS - Continuous Deployment"
      environment: GitHub
      strategy:
        runOnce:
          deploy:
            steps:
              - task: GitVersion@4
                displayName: GitVersion
              - task: GitHubRelease@0
                inputs:
                  gitHubConnection: "SFA"
                  repositoryName: "$(Build.Repository.Name)"
                  action: "create"
                  target: "$(Build.SourceVersion)"
                  tagSource: "manual"
                  tag: "$(Build.BuildNumber)"
                  addChangeLog: true
                  assets: "$(System.DefaultWorkingDirectory)/Infrastructure-Scripts/**/*.ps1"
